config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/auth/twitter", as: :login
  get "/auth/twitter/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:update]
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true,
            length: {is: 2},
            format: {with: /[A-Z]/, message: "Please use two capital letters"}
  validates :zip_code, presence: true,
                       length: {is: 5}
  validates :sha, uniqueness: true

  before_validation :generate_sha

  belongs_to :user

  has_many :legislators, through: :address_legislators
  has_many :address_legislators, dependent: :destroy

  def convert_to_lat_long_for_user
    if self.user
      lat_long = Geocoder.coordinates(self.street + ", " +
                                      self.city + ", " +
                                      self.state + ", " +
                                      self.zip_code)
      self.user.update_attributes(latitude: lat_long[0], longitude: lat_long[1])
    end
  end

  def generate_sha
    self.sha = Digest::SHA1.hexdigest(self.street.to_s + self.zip_code.to_s)
  end
end

app/models/address_legislator.rb
class AddressLegislator < ActiveRecord::Base
  belongs_to :address
  belongs_to :legislator
end

app/models/bill.rb
class Bill < OpenStruct
  def self.service
    @service ||= SunlightService.new
  end

  def self.where(params)
    if params[:leg_id]
      service.state_bills(params[:leg_id]).map {|bill| Bill.new(bill)}
    else
      service.national_bills(params[:bioguide_id]).map {|bill| Bill.new(bill)}
    end
  end

  def extant_title
    short_title || official_title
  end

  def link
    urls[:opencongress] if urls
  end
end

app/models/funding.rb
class Funding < OpenStruct
  def self.service
    @service ||= SunlightService.new
  end

  def self.total_contributions(fec_ids)
    specific_funding_data(fec_ids, :total_contributions)
  end

  def self.cash_on_hand(fec_ids)
    specific_funding_data(fec_ids, :cash_on_hand)
  end

  private

  def self.all_funding_data(fec_ids)
    service.national_congressperson_funding(fec_ids)
  end

  def self.specific_funding_data(fec_ids, key)
    all_funding_data(fec_ids).reduce(0) {|sum, data| sum + data[key].to_f }
  end
end

app/models/legislator.rb
class Legislator < ActiveRecord::Base
  validates :sha, uniqueness: true

  before_validation :generate_sha

  has_many :addresses, through: :address_legislators
  has_many :address_legislators

  def generate_sha
    self.sha = Digest::SHA1.hexdigest(self.first_name.to_s + self.votesmart_id.to_s)
  end

  def combined_name
    first_name + " " + last_name
  end

  def bills
    if leg_id
      Bill.where(leg_id: leg_id)
    else
      Bill.where(bioguide_id: bioguide_id)
    end
  end

  def total_contributions
    Funding.total_contributions(parsed_fec_ids) if fec_ids
  end

  def cash_on_hand
    Funding.cash_on_hand(parsed_fec_ids) if fec_ids
  end

  def parsed_fec_ids
    eval(fec_ids)
  end
end

app/models/location_legislators_creator.rb
class LocationLegislatorsCreator
  attr_reader :service, :current_user

  def initialize(current_user)
    @current_user = current_user
    @service ||= SunlightService.new
  end

  def create_legislators
    service.state_legislators_by_location(current_user).each do |params|
      legislator = Legislator.find_or_create_by(full_name: params[:full_name],
                                    first_name: params[:first_name],
                                     last_name: params[:last_name],
                                  votesmart_id: params[:votesmart_id].to_s,
                                        leg_id: params[:leg_id],
                           transparencydata_id: params[:transparencydata_id],
                                         level: params[:level],
                                       chamber: params[:chamber],
                                         party: params[:party],
                                         email: params[:email])

      associate_user_with_legislator(legislator)
    end

    service.national_legislators_by_location(current_user).each do |params|

      legislator = Legislator.find_or_create_by(first_name: params[:first_name],
                                     last_name: params[:last_name],
                                  votesmart_id: params[:votesmart_id].to_s,
                                   bioguide_id: params[:bioguide_id],
                                       fec_ids: params[:fec_ids],
                                         level: "national",
                                         phone: params[:phone],
                                       chamber: params[:chamber],
                                         party: params[:party],
                                         email: params[:oc_email])

      associate_user_with_legislator(legislator)
    end
  end

  def associate_user_with_legislator(legislator)
    AddressLegislator.create(address: current_user.address,
                          legislator: legislator)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :screen_name, uniqueness: true
  has_one :address, dependent: :destroy
  delegate :legislators, to: :address

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end

  def state_legislators
    legislators.where(level: "state")
  end

  def state_representatives
    legislators.where(level: "state", chamber: "lower")
  end

  def state_senators
    legislators.where(level: "state", chamber: "upper")
  end

  def national_legislators
    legislators.where(level: "national")
  end

  def national_representatives
    legislators.where(level: "national", chamber: "house")
  end

  def national_senators
    legislators.where(level: "national", chamber: "senate")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def create_legislators
    LocationLegislatorsCreator.new(current_user).create_legislators
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    if current_user
      session[:user_id] = nil
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    @address = Address.new(address_params) #creating address updates user object
    if @address.save
      current_user.address = @address
      @address.convert_to_lat_long_for_user
      create_legislators
      redirect_to root_path
    else
      render "welcome/index"
    end
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :zip_code)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @address = Address.new
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="row">
    <div class="bottom-aligned-text col-lg-12 text-center">
      <p>Copyright &copy; Travis Haby 2015</p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Policurious</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <li><%= link_to ("Hello, " + current_user.screen_name), root_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Political dashboard based on location">
  <meta name="author" content="Travis Haby">

  <title>Policurious</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/navbar" %>

  <%= yield %>

  <%= render partial: "layouts/footer" %>

</body>
</html>

app/views/users/_update_profile.html.erb
<div class="container center" id="update-address-notice">
  <div class="well text-center">
    <h3>Almost there!</h3><br>
    <h4>Please update your profile with your address
    to see information about your area's politicians:</h4>
    <br>
    <%= bootstrap_form_for @address,
                          inline_errors: true,
                          url: user_path(current_user),
                          method: :put do |f| %>
    <%= f.text_field :street %>
    <%= f.text_field :city %>
    <%= f.text_field :state %>
    <%= f.text_field :zip_code %>
    <%= f.submit "Update Profile" %>
    <% end %>
  </div>
</div>

app/views/welcome/_guest.html.erb
<div class="row">
  <div class="col-sm-offset-3 col-sm-6 text-center">
    <h1 class="well grey-well">Please <%= link_to "login", login_path %> to view your dashboard.</h1>
  </div>
</div>

app/views/welcome/_logged_in.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6 text-center small-space well shadow">
    <h1><%= current_user.screen_name.capitalize %>'s Policurious Dashboard</h1>
  </div>
</div>
<div class="row text-center" id="legislators-row">
  <div class="col-sm-4 col-sm-offset-1" id="state-legislators">
    <h3 class="well shadow">State Level</h3>
    <div class="row well well-sm shadow" id="State Representatives">
      <h4><strong>State Representative</strong></h4>
      <% current_user.state_representatives.each do |representative| %>
      <div>
        <h4 class="party-<%= representative.party[0] %> small-space"><%= representative.full_name  %></h4>
        <div class="small-space">
          <h5>Funding Data:</h5>
          <ul class="text-left list-group" id="<%= representative.last_name.parameterize %>-funding">
              <li class="list-group-item">Funding data not provided for state legislators.</li>
          </ul>
        </div>
        <div class="small-space">
          <h5>Bills Sponsored:</h5>
          <ul class="text-left list-group" id="<%= representative.last_name.parameterize %>-bills">
            <% representative.bills.each do |bill| %>
              <li  class="list-group-item"><span class="underline">Session <%= bill.session %>:</span>  <%= bill.title %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
    <div class="row well well-sm" id="State Senators">
      <h4><strong>State Senator</strong></h4>
      <% current_user.state_senators.each do |senator| %>
        <div>
          <h4 class="party-<%= senator.party[0] %> small-space"><%= senator.full_name %></h4>
          <div class="small-space">
            <h5>Funding Data:</h5>
            <ul class="text-left list-group" id="<%= senator.last_name.parameterize %>-funding">
                <li class="list-group-item">Funding data not provided for state legislators.</li>
            </ul>
          </div>
          <div class="small-space">
            <h5>Bills Sponsored:</h5>
            <ul class="text-left list-group" id="<%= senator.last_name.parameterize %>-bills">
              <% senator.bills.each do |bill| %>
                <li class="list-group-item"><span class="underline">Session <%= bill.session %>:</span>  <%= bill.title %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-4 col-sm-offset-2" id="national-congresspeople">
    <h3 class="well shadow">National Level</h3>
    <div class="row well well-sm shadow" id="national-representatives">
      <h4><strong>National Representative</strong></h4>
      <% current_user.national_representatives.each do |representative| %>
        <div>
          <h4 class="party-<%= representative.party[0] %> small-space"><%= representative.combined_name %></h4>
          <div class="small-space">
            <h5>Funding Data:</h5>
            <ul class="text-left list-group" id="<%= representative.last_name.parameterize %>-funding">
              <li class="list-group-item">Total contributions: $<%= number_with_delimiter(representative.total_contributions) %></li>
              <li class="list-group-item">Cash on hand: $<%= number_with_delimiter(representative.cash_on_hand) %></li>
            </ul>
          </div>
          <div class="small-space">
            <h5>Bills Sponsored:</h5>
            <ul class="text-left list-group" id="<%= representative.combined_name.parameterize %>-bills">
              <% representative.bills.each do |bill| %>
                <li class="list-group-item"><span class="underline">Congress <%= bill.congress %>:</span>  <a href="<%=bill.link%>"><%= bill.extant_title %></a></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row well well-sm" id="national-senators">
      <h4><strong>National Senators</strong></h4>
      <% current_user.national_senators.each do |senator| %>
        <div>
          <h4 class="party-<%= senator.party[0] %> small-space"><%= senator.combined_name %></h4>
          <div class="small-space">
            <h5>Funding Data:</h5>
            <ul class="text-left list-group" id="<%= senator.last_name.parameterize %>-funding">
              <li class="list-group-item">Total contributions: $<%= number_with_delimiter(senator.total_contributions) %></li>
              <li class="list-group-item">Cash on hand: $<%= number_with_delimiter(senator.cash_on_hand) %></li>
            </ul>
          </div>
          <div class="small-space">
            <h5>Bills Sponsored:</h5>
            <ul class="text-left list-group" id="<%= senator.combined_name.parameterize %>-bills">
              <% senator.bills.each do |bill| %>
                <li class="list-group-item"><span class="underline">Congress <%= bill.congress %>:</span>  <a href="<%=bill.link%>"><%= bill.extant_title %></a></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if current_user && current_user.address.nil? %>
  <%= render partial: "users/update_profile" %>
<% elsif current_user %>
  <%= render partial: "welcome/logged_in" %>
<% else %>
  <%= render partial: "welcome/guest" %>
<% end %>